config/routes.rb
OpenLets::Application.routes.draw do

  root :to => 'pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      post 'direct_transfer'
      get  'transfer'
    end
  end
  
  resources :items do
    member do
      post 'purchase'
      put  'pause'
      put  'activate'
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      get  'fulfill'
      put  'close'
      post 'create_wish_offer'
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/home"

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  include Workflow
  include WorkflowExtended

  mount_uploader :image, ImageUploader	
  attr_accessible :image, :title, :user_id, :description, :category_ids

  belongs_to :user
  has_many   :category_connections, as: :categoriable, dependent: :destroy
  has_many   :categories, through: :category_connections
  has_many   :items
  has_one    :location,  as: :locationable, dependent: :destroy

  validates_presence_of :title
  
  scope :of_approved_users, lambda { where(user_id: User.approved.pluck(:id)) }

  workflow do
    state :active do
      event :pause, transitions_to: :paused
      event :ban,   transitions_to: :banned
    end
    state :paused do
      event :reactivate, transitions_to: :active
    end
    state :banned do
      event :reactivate, transitions_to: :active
    end
  end
  workflow_scopes

  scope :not_mine, lambda { |user| where('user_id != ?', user.id) }

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
	load_and_authorize_resource
	before_filter :load_wish, :only => [:show, :create_wish_offer, :fulfill]

	def new
		@wish = current_user.wishes.new
	end

	def create
		@wish = current_user.wishes.new(params[:wish])
		if @wish.save 
			redirect_to @wish
		else 
			render 'new'
		end
	end

	def close
		@wish.close!
		redirect_to @wish	
	end

	def show
	end

	def index
		@wishes = Wish.of_approved_users.active - current_user.wishes
	end

	def edit
		@wish = current_user.wishes.find(params[:id])
	end

	def update
		@wish = current_user.wishes.find(params[:id])
		if @wish.update_attributes(params[:wish])
			redirect_to @wish
		else
			render 'edit'
		end
	end

	def fulfill
		@item = current_user.items.new(title: @wish.title, image: @wish.image.url, 
														description: @wish.description, wish_id: @wish.id)
	end

	def create_wish_offer
    @item = current_user.items.new(params[:item])
    @item.wish_id = params[:id]
    @item.image = @wish.image unless @item.image.present?
    if @item.save
      flash[:notice] = "Created item successfuly"
      Mailer.wish_fulfilled(@item).deliver
      redirect_to @item
    else
      render 'fulfill'
    end		
	end

	private

		def load_wish
			@wish = Wish.find(params[:id])
		end

end

app/views/wishes/_form.html.slim
= simple_form_for(@wish, defaults: { label: false }) do |f|
  = f.error_notification
  - f.object.errors.full_messages.each do |message|
    p= message

  .field
    = f.input :title, placeholder: 'Title'   
  .field
    = f.input :description, placeholder: 'Description'
  .field
    = f.association :categories, label_method: :full_name, input_html: { class: 'chzn-select', "data-placeholder" => 'Categories' }
  - unless @wish.new_record?
    .field
      = image_tag(@wish.image, size: "50x50")
  br
  .field
    = f.input :image
  .actions = f.submit 'Save', class: 'button radius expand'

app/views/wishes/_table.slim
table
  tr
    th Title
    th Image
    th User
    th
    th
    th

  - wishes.each do |wish|
    tr
      td = wish.title
      td = image_tag(wish.image, size: "40x40")
      td = wish.user_id
      td = link_to 'Show', wish
      - if can? :update, wish
        td = link_to 'Edit', edit_wish_path(wish)
        td = link_to 'Close', close_wish_path(wish), confirm: 'Are you sure?', method: :put

app/views/wishes/_wish_offer_form.slim
= simple_form_for(@item, url: create_wish_offer_wish_path, method: :post, defaults: { label: false }) do |f|
  = f.error_notification
  - f.object.errors.full_messages.each do |message|
    p= message

  .field
    = f.input :title, placeholder: 'Title'   
  .field
    = f.input :description, placeholder: 'Description'
  .field
    = f.association :categories, input_html: { class: 'chzn-select' }
  .field
    = f.input :price, placeholder: 'Price'
  .field
    = image_tag(@wish.image, size: "50x50")
  .field
    = f.input :image
  .actions = f.submit 'Save'

app/views/wishes/edit.slim
h1 Editing Wish

== render 'form'

= link_to 'Show', @wish
'|
= link_to 'Back', wishes_path

app/views/wishes/fulfill.slim
h1= "Fulfill #{@wish.user.name.pluralize} Wish"
h3= "Wish Title: #{@wish.title}"
h3= "Wish Title: #{@wish.description}"

== render 'wish_offer_form' 

= link_to 'Back', wish_path(@wish), class: 'button radius small'

app/views/wishes/index.html.slim
h1 Listing wishes
= render 'table', wishes: @wishes

br

= link_to new_wish_path, class: "small button"
	i.fa.fa-magic
	'  New Wish

app/views/wishes/new.html.slim
.row
  .large-12.columns
    h1 New wish
    == render 'form'

app/views/wishes/show.html.slim
p#notice = notice

= link_to 'fulfill the wish', fulfill_wish_path(@wish), class: 'button radius large' if can? :fulfill, @wish

p
  strong Title:
  = @wish.title
p
  strong Description:
  = @wish.description
p
  strong Image:
  = image_tag(@wish.image, size: "50x50")
p
  strong User:
  = @wish.user_id



= link_to 'Edit', edit_wish_path(@wish), class: 'button radius secondary' if can? :update, @wish
= link_to 'Back', wishes_path, class: 'button radius'

br
br

h3 Wish Propositions

= render 'items/table', items: @wish.items