config/routes.rb
OpenLets::Application.routes.draw do

  root :to => 'pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      post 'direct_transfer'
      get  'transfer'
    end
  end
  
  resources :items do
    member do
      post 'purchase'
      put  'pause'
      put  'activate'
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      get  'fulfill'
      put  'close'
      post 'create_wish_offer'
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/home"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Workflow
  include WorkflowExtended

  devise :database_authenticatable, :registerable, :recoverable, 
         :rememberable, :trackable, :validatable, :omniauthable, :token_authenticatable
  
  attr_accessible :email, :password, :password_confirmation, :name, :about, :locale, :locations_attributes
  
  validates_presence_of :email
  
  mount_uploader :image, ImageUploader

  has_many :authorizations, dependent: :destroy
  has_many :items,          dependent: :destroy
  has_many :wishes,         dependent: :destroy
  has_many :transactions,   dependent: :destroy
  has_many :purchases, foreign_key: 'buyer_id',  class_name: 'Transaction'
  has_many :sales,     foreign_key: 'seller_id', class_name: 'Transaction'

  has_many :user_conversations, class_name: 'Conversation', foreign_key: 'user_id'
  has_many :messages
  has_many :comments

  has_many :locations, as: :locationable, dependent: :destroy
  accepts_nested_attributes_for :locations

  after_create :registration_gift

  scope :awaiting_approval, lambda { where(workflow_state: 'awaiting_approval') }
  scope :approved,          lambda { where(workflow_state: 'approved') }
  scope :banned,            lambda { where(workflow_state: 'banned') }

  LOCALES = ['en', 'he']

  workflow do
    state :awaiting_approval do
      event :approve, transitions_to: :approved
      event :ban, transitions_to: :banned
    end
    state :approved do
      event :ban, transitions_to: :banned
    end
    state :banned do
      event :approve, transitions_to: :approved
    end
  end

  def conversations
    Conversation.where("user_id = ? OR second_user_id = ?", id, id)
  end

  def allowed_messages
    cids = conversations.map(&:id)
    Message.where(conversation_id: cids)
  end

  def account_balance
    sales.sum(&:amount) - purchases.sum(&:amount)
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s, token: auth.credentials.token, secret: auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0,10]
        user.name = auth.info.name
        user.email = auth.info.email
        user.save
      end
      authorization.username = auth.info.nickname
      authorization.user_id = user.id
      authorization.save
    end
    authorization.user
  end

  private

    def registration_gift
      Transaction.registration_gift(self)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :set_user
  before_filter :validate_authorization_for_user, only: [:edit, :update]

  def items
    @items = @user.items
  end

  def show
    if current_user
      id = current_user.id
      @conversation = Conversation.where("user_id = ? AND second_user_id = ? OR user_id = ? AND second_user_id = ?", id, id, id, id).first
    end
  end

  def edit
    @user.locations.build unless @user.locations.any?
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def transfer
    @transaction = Transaction.new
  end

  def direct_transfer
    @transaction = @user.sales.new(params[:transaction])
    @transaction.transaction_type = 'direct_transfer'
    @transaction.buyer_id = current_user.id
    if @transaction.save
      flash[:notice] = "successfully transfered funds"
      redirect_to @user
    else
      render 'transfer'
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

  end

app/views/users/_form.slim
= simple_form_for @user do |f|
  = f.error_notification
  .form-inputs
    .row
      .large-6.columns
        = f.input :name, :required => true, :autofocus => true
        = f.input :locale, :required => true, collection: User::LOCALES
      .large-6.columns
        = f.simple_fields_for :locations do |l|
          = l.input :address
        .panel.callout#map

  .form-actions
    = f.button :submit
div
  h1 Connect Account
  - ['facebook', 'linkedin', 'google_oauth2'].each do |provider|
    - if current_user.authorizations.pluck(:provider).include?(provider.to_s)
      = provider.to_s.titleize
      | Connected
    - else
      = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider)
    br

app/views/users/edit.html.erb
<div class="row">
  <div class="large-12 columns">

    <h1>Editing user</h1>

    <%= render 'form' %>

  </div>

</div>
<script>

$(function() {
  $('input#user_locations_attributes_0_address').geocomplete({
    map: "#map",
    markerOptions: {
      draggable: true
    },
    location: "<%= current_user.locations.first.try(:address) %>"
  });
});

</script>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/items.slim
table.responsive
  thead
    tr
      th title
      th price

  tbody
    - @items.each do |item|
      tr
        td= item.title
      tr
        td= item.price        

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.slim
.row
	.item-panel
		.large-2.small-4.columns
			= (image_tag @user.image_url(:thumb).to_s)
		.large-6.small-8.columns
			h1= @user.name
			h3= "Balance: #{@user.account_balance}"
			- if can? :update, @user
				= link_to "Edit Profile", edit_user_path(@user), class: 'button radius tiny'
		.large-4.columns
			br
			br
			- if @conversation
				.small-12.columns
			  	= link_to "Send Message", conversation_messages_path(@conversation), class: 'button radius large expand'
			- if cannot? :update, @user
				.small-6.columns
					= link_to "Send Message", new_conversations_path(@user), class: 'button radius expand'
				.small-6.columns
					= link_to "Send Money", transfer_user_path(@user), class: 'button radius expand'
		.clear-both
	  
.row
	.large-12.columns
		h1.text-center Items for Sale
		= render 'items/table', items: @user.items

		h1 Wishes
		= render 'wishes/table', wishes: @user.wishes

		h1 Sales
		= render 'transactions/table', transactions: @user.sales

		h1 Purchases
		= render 'transactions/table', transactions: @user.purchases

app/views/users/transfer.slim
- if @user != current_user
  h1= "Send #{@user.name} Some blablas"
  = simple_form_for([@user, @transaction], url: direct_transfer_user_path(@user) , defaults: { label: false }) do |f|
    = f.error_notification
    - f.object.errors.full_messages.each do |message|
      p= message  

    = f.input :amount, placeholder: 'amount'
    = f.submit 'Submit', class: 'button radius'