config/routes.rb
OpenLets::Application.routes.draw do

  root :to => 'pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      post 'direct_transfer'
      get  'transfer'
    end
  end
  
  resources :items do
    member do
      post 'purchase'
      put  'pause'
      put  'activate'
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      get  'fulfill'
      put  'close'
      post 'create_wish_offer'
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/home"

end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  include Workflow
  include WorkflowExtended

  attr_accessible :description, :price, :title, :image, :category_ids, :wish_id

  belongs_to :user
  belongs_to :wish
  has_many   :category_connections, as: :categoriable, dependent: :destroy
  has_many   :categories, through: :category_connections
  has_many   :transactions
  has_many   :buyers, through: :transactions
  has_many   :comments,  as: :commentable
  has_one    :location,  as: :locationable, dependent: :destroy

  validates_presence_of :description, :price, :title
  validates_numericality_of :price

  after_create :item_gift

  scope :of_approved_users, lambda { where(user_id: User.approved.pluck(:id)) }

  workflow do
    state :active do
      event :ban,     transitions_to: :banned
      event :pause,   transitions_to: :paused
    end
    state :paused do
      event :activate, transitions_to: :active
      event :ban,     transitions_to: :banned
    end
    state :banned do
      event :activate, transitions_to: :active
      event :pause,   transitions_to: :paused      
    end
  end
  workflow_scopes
  
  def purchase!(buyer)
    if buyer.account_balance >= price
      Transaction.purchase!(buyer, user, self)
    else
      false
    end
  end

  private

    def item_gift
      Transaction.item_gift(self)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :load_item, :only => [:edit, :update, :show, :purchase, :pause, :activate]

  def purchase
    if @item.purchase!(current_user)
      flash[:notice] = "Payment was successful"
      Mailer.item_purchased(@item, current_user).deliver
      redirect_to @item
    else
      @comments = @item.comments.order(:created_at)
      @comment  = @item.comments.new
      flash[:alert] = "Insufficient Funds"
      render 'show'
    end
  end

  def show
    @comments = @item.comments.order(:created_at)
    @comment  = @item.comments.new
  end

  def new
    @item = current_user.items.new
    @categories = Category.all
  end

  def create
    @item = current_user.items.new(params[:item])
    if @item.save
      flash[:notice] = "Created item successfuly"
      redirect_to @item
    else
      render 'new'
    end
  end

  def pause
    @item.pause!
    flash[:notice] = "Item is paused"
    redirect_to @item
  end

  def activate
    @item.activate!
    flash[:notice] = "Item is active!"
    redirect_to @item
  end

  def update
    if @item.update_attributes(params[:item]) 
      redirect_to items_path, :notice => "Updated item successfuly"
    else
      render 'edit'
    end
  end

  def index
    @items = Item.of_approved_users.active
  end

  private
  
    def load_item
      @item = Item.find(params[:id])
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= simple_form_for(@item, defaults: { label: false }) do |f|
  = f.error_notification
  - f.object.errors.full_messages.each do |message|
    p= message

  .field
    = f.input :title, placeholder: 'Title'   
  .field
    = f.input :description, placeholder: 'Description'
  .field
    = f.association :categories, label_method: :full_name, input_html: { class: 'chzn-select', "data-placeholder" => 'Categories' }
  .field
    = f.input :price, placeholder: 'Price'
  - unless @item.new_record?
    .field
      = image_tag(@item.image, size: "50x50")
  .field
    = f.input :image
  .actions = f.submit 'Save', class: 'button radius expand'

app/views/items/_table.slim
- items.each do |item|
  .row.marketplace
    .item-panel
      .large-3.small-3.columns      
        = image_tag(item.image)
      .large-6.small-6.columns  
        h3= link_to item.title, item
        p= "Price: #{item.price} #{Setting[:currency_name].capitalize.pluralize}"
        = link_to item.user.try(:name), item.user
      .large-3.small-3.columns
        .row
          .large-12.columns
          - if item.user != current_user
              = link_to "Purchase", purchase_item_path(item), class: 'button radius right small', method: :post, confirm: 'Are you sure?'
        .row
          .large-12.columns
            - if can? :update, item
              td= link_to edit_item_path(item), class: 'button radius tiny right'
                .i.fa.fa-edit
            - if can? :pause, item
              td= link_to pause_item_path(item), confirm: 'Are you sure?', method: :put, class: 'button radius tiny right alert'
                .i.fa.fa-pause
            - if can? :activate, item
              td= link_to activate_item_path(item), method: :put, class: 'button radius tiny right'
                .i.fa.fa-play
      .clear-both

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'|
= link_to 'Back', items_path

app/views/items/index.html.slim
.row
  .large-12.columns
    h1 Marketplace
    = render 'table', items: @items

app/views/items/new.html.slim
.row
  .large-12.columns
    h1 Add an Item
    == render 'form'

app/views/items/show.html.slim
.row
  .item-panel
    .large-3.columns
      p= image_tag(@item.image)
    .large-5.columns
      h1= @item.title
      p= link_to @item.user.name, @item.user
      p
        strong= @item.description
      p
        strong Price:
        = @item.price
      p
        strong Status:
        = @item.workflow_state  
    .large-4.columns
      - if @item.user != current_user
        = link_to "Purchase for #{@item.price} #{curreny_name.capitalize.pluralize}", purchase_item_path(@item), class: 'button radius right expand large', method: :post, id: 'purchase-button'
    
    .row
      .large-12.columns
        - if can? :update, @item
          = link_to 'Edit', edit_item_path(@item), class: 'button radius secondary tiny'        
        - if can? :update, @item
          td = link_to 'Edit', edit_item_path(@item), class: 'button radius tiny'
        - if can? :pause, @item
          td = link_to 'Pause', pause_item_path(@item), confirm: 'Are you sure?', method: :put, class: 'button radius tiny alert'
        - if can? :activate, @item
          td = link_to 'Reactivate', activate_item_path(@item), method: :put, class: 'button radius tiny'

.row#comments
  .large-12.columns
    = render 'comments/list'