config/routes.rb
OpenLets::Application.routes.draw do

  root :to => 'pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      post 'direct_transfer'
      get  'transfer'
    end
  end
  
  resources :items do
    member do
      post 'purchase'
      put  'pause'
      put  'activate'
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      get  'fulfill'
      put  'close'
      post 'create_wish_offer'
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/home"

end

app/views/layouts/_flash_messages.slim
- if flash[:notice]
  .alert-box.success data-alert=""
    = flash[:notice]
    a.close href="" x
- if flash[:error]
  .notice
    = flash[:error]
    a.close href="" x
- if flash[:alert]
  .alert-box.alert data-alert=""
    = flash[:alert]
    a.close href="" x

app/views/layouts/_top_bar.slim
.fixed
  nav.top-bar data-topbar=""
    ul.title-area
      li.name
        h1#logo
          = link_to root_path
            = image_tag('float-logo-1.png', size: "30x30")
            span penLETS

      li.toggle-topbar.menu-icon
        a href="#"
          span
    section.top-bar-section
      ul.right
        - if user_signed_in?
          li= link_to new_item_path
            i.fa.fa-plus
            |  Add Item
          li.divider
          li= link_to "Make a Wish", new_wish_path
          li.divider
          li= link_to items_path
            i.fa.fa-shopping-cart
            |  Market
          li.divider        
          li= link_to wishes_path
            i.fa.fa-magic
            |  Wishes
          li.divider
          li=link_to current_user
            i.fa.fa-user
            |  Profile
          li.divider
          li= link_to conversations_path
            i.fa.fa-inbox
            |  Inbox
          li.divider
          li= link_to destroy_user_session_path
            i.fa.fa-sign-out
            |  Logout
        - else
          li= link_to new_user_session_path
            i.fa.fa-sign-in
            |  Login

app/views/layouts/application.slim
doctype
/! paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/![if lt IE 7 ] <html class="ie6" lang="en">
/![if IE 7 ] <html class="ie7" lang="en">
/![if IE 8 ] <html class="ie8" lang="en">
/! [if (gte IE 9)|!(IE)]><!
html lang="en"
  /! <![endif]
  head
    meta charset="utf-8"
    /! Uncomment to make IE8 render like IE7
    /! <meta http-equiv="X-UA-Compatible" content="IE=7" />
    /! Set the viewport width to device width for mobile
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : Setting.find_by_name('community_name').value
    link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'

    = stylesheet_link_tag    "application"
    script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body[class="#{@dir}" ]
    = render 'layouts/top_bar'
    = render 'layouts/flash_messages'
    = yield